# Generated by Django 5.0.7 on 2024-08-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
