# Generated by Django 5.0.7 on 2024-08-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_image_active_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
    ]
