# Generated by Django 5.0.7 on 2024-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_remove_image_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
